sudo: false
language: php
php:
  - 5.6
  - 7
  - 7.1

cache:
  directories:
  - $HOME/.composer/cache

script:
  - phpunit --configuration tests/phpunit.xml

before_script:
  - composer install -d web/

