---
# Baikal installation

  - name: download baikal
    command: wget -q -O /tmp/baikal.zip https://github.com/fruux/Baikal/releases/download/0.4.6/baikal-0.4.6.zip

  - name: unzip baikal
    command: /usr/bin/unzip /tmp/baikal.zip -d /var/www
    sudo: yes

  - name: baikal permissions
    file: path=/var/www/baikal state=directory recurse=yes mode=0755 owner=www-data group=www-data
    sudo: yes

  - name: baikal configuration (1/2)
    copy: src=baikal/config.php dest=/var/www/baikal/Specific owner=www-data group=www-data mode=600 backup=yes
    sudo: yes

  - name: baikal configuration (2/2)
    copy: src=baikal/config.system.php dest=/var/www/baikal/Specific owner=www-data group=www-data mode=600 backup=yes
    sudo: yes

  - name: baikal database
    copy: src=baikal/db.sqlite dest=/var/www/baikal/Specific/db owner=www-data group=www-data mode=600 backup=yes
    sudo: yes
